[package]
name = "blueplug"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.1"
btsensor = "0.1.0"
futures = "0.3.29"
tokio = { version = "1.34.0", features = ["full"] }
uuid = "1.5.0"
async-trait = "0.1.74"
color-eyre = "0.6.2"
ruuvi-sensor-protocol = "0.6.1"

